server:
  port: 8030
  servlet:
    context-path: /api
spring:
  session:
    store-type: redis
  application:
    name: oj-user-service
  main:
    allow-circular-references: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 844c4ae7-0b2a-4dcb-b82a-db91e3ce24af #nacos名称空间
        password: nacos