server:
  port: 88
spring:
  application:
    name: oj-gateway
  main:
    allow-circular-references: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 844c4ae7-0b2a-4dcb-b82a-db91e3ce24af #nacos名称空间
        password: nacos
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: userService
          uri: lb://oj-user-service
          predicates:
            - Path=/api/user/**
        - id: thirdParty
          uri: lb://api-third-party
          predicates:
            - Path=/api/oauth/**,/api/alipay/**
        - id: apiOrder
          uri: lb://api-order
          predicates:
            - Path=/api/order/**
        - id: api
          uri: lb://api
          predicates:
            - Path=/api/**